package Noyau;

import java.awt.desktop.SystemSleepEvent;
import java.util.ArrayList;
import java.util.Arrays;

public final class BDD {


    public static ArrayList<String> bd = new ArrayList<String>(
            Arrays.asList("BDD/s1/1.pgm", "BDD/s1/2.pgm", "BDD/s1/3.pgm",  "BDD/s1/4.pgm", "BDD/s1/5.pgm",
                    "BDD/s2/1.pgm", "BDD/s2/2.pgm", "BDD/s2/3.pgm",  "BDD/s2/4.pgm", "BDD/s2/5.pgm",
                    "BDD/s3/1.pgm", "BDD/s3/2.pgm", "BDD/s3/3.pgm",  "BDD/s3/4.pgm", "BDD/s3/5.pgm",
                    "BDD/s4/1.pgm", "BDD/s4/2.pgm", "BDD/s4/3.pgm",  "BDD/s4/4.pgm", "BDD/s4/5.pgm",
                    "BDD/s5/1.pgm", "BDD/s5/2.pgm", "BDD/s5/3.pgm",  "BDD/s5/4.pgm", "BDD/s5/5.pgm",
                    "BDD/s6/1.pgm", "BDD/s6/2.pgm", "BDD/s6/3.pgm",  "BDD/s6/4.pgm", "BDD/s6/5.pgm",
                    "BDD/s7/1.pgm", "BDD/s7/2.pgm", "BDD/s7/3.pgm",  "BDD/s7/4.pgm", "BDD/s7/5.pgm",
                    "BDD/s8/1.pgm", "BDD/s8/2.pgm", "BDD/s8/3.pgm",  "BDD/s8/4.pgm", "BDD/s8/5.pgm",
                    "BDD/s9/1.pgm", "BDD/s9/2.pgm", "BDD/s9/3.pgm",  "BDD/s9/4.pgm", "BDD/s9/5.pgm",
                    "BDD/s10/1.pgm", "BDD/s10/2.pgm", "BDD/s10/3.pgm",  "BDD/s10/4.pgm", "BDD/s10/5.pgm",
                    "BDD/s11/1.pgm", "BDD/s11/2.pgm", "BDD/s11/3.pgm",  "BDD/s11/4.pgm", "BDD/s11/5.pgm",
                    "BDD/s12/1.pgm", "BDD/s12/2.pgm", "BDD/s12/3.pgm",  "BDD/s12/4.pgm", "BDD/s12/5.pgm",
                    "BDD/s13/1.pgm", "BDD/s13/2.pgm", "BDD/s13/3.pgm",  "BDD/s13/4.pgm", "BDD/s13/5.pgm",
                    "BDD/s14/1.pgm", "BDD/s14/2.pgm", "BDD/s14/3.pgm",  "BDD/s14/4.pgm", "BDD/s14/5.pgm",
                    "BDD/s15/1.pgm", "BDD/s15/2.pgm", "BDD/s15/3.pgm",  "BDD/s15/4.pgm", "BDD/s15/5.pgm",
                    "BDD/s16/1.pgm", "BDD/s16/2.pgm", "BDD/s16/3.pgm",  "BDD/s16/4.pgm", "BDD/s16/5.pgm",
                    "BDD/s17/1.pgm", "BDD/s17/2.pgm", "BDD/s17/3.pgm",  "BDD/s17/4.pgm", "BDD/s17/5.pgm",
                    "BDD/s18/1.pgm", "BDD/s18/2.pgm", "BDD/s18/3.pgm",  "BDD/s18/4.pgm", "BDD/s18/5.pgm",
                    "BDD/s19/1.pgm", "BDD/s19/2.pgm", "BDD/s19/3.pgm",  "BDD/s19/4.pgm", "BDD/s19/5.pgm",
                    "BDD/s20/1.pgm", "BDD/s20/2.pgm", "BDD/s20/3.pgm",  "BDD/s20/4.pgm", "BDD/s20/5.pgm",
                    "BDD/s21/1.pgm", "BDD/s21/2.pgm", "BDD/s21/3.pgm",  "BDD/s21/4.pgm", "BDD/s21/5.pgm",
                    "BDD/s22/1.pgm", "BDD/s22/2.pgm", "BDD/s22/3.pgm",  "BDD/s22/4.pgm", "BDD/s22/5.pgm",
                    "BDD/s23/1.pgm", "BDD/s23/2.pgm", "BDD/s23/3.pgm",  "BDD/s23/4.pgm", "BDD/s23/5.pgm",
                    "BDD/s24/1.pgm", "BDD/s24/2.pgm", "BDD/s24/3.pgm",  "BDD/s24/4.pgm", "BDD/s24/5.pgm",
                    "BDD/s25/1.pgm", "BDD/s25/2.pgm", "BDD/s25/3.pgm",  "BDD/s25/4.pgm", "BDD/s25/5.pgm",
                    "BDD/s26/1.pgm", "BDD/s26/2.pgm", "BDD/s26/3.pgm",  "BDD/s26/4.pgm", "BDD/s26/5.pgm",
                    "BDD/s27/1.pgm", "BDD/s27/2.pgm", "BDD/s27/3.pgm",  "BDD/s27/4.pgm", "BDD/s27/5.pgm",
                    "BDD/s28/1.pgm", "BDD/s28/2.pgm", "BDD/s28/3.pgm",  "BDD/s28/4.pgm", "BDD/s28/5.pgm",
                    "BDD/s29/1.pgm", "BDD/s29/2.pgm", "BDD/s29/3.pgm",  "BDD/s29/4.pgm", "BDD/s29/5.pgm",
                    "BDD/s30/1.pgm", "BDD/s30/2.pgm", "BDD/s30/3.pgm",  "BDD/s30/4.pgm", "BDD/s30/5.pgm",
                    "BDD/s31/1.pgm", "BDD/s31/2.pgm", "BDD/s31/3.pgm",  "BDD/s31/4.pgm", "BDD/s31/5.pgm",
                    "BDD/s32/1.pgm", "BDD/s32/2.pgm", "BDD/s32/3.pgm",  "BDD/s32/4.pgm", "BDD/s32/5.pgm",
                    "BDD/s33/1.pgm", "BDD/s33/2.pgm", "BDD/s33/3.pgm",  "BDD/s33/4.pgm", "BDD/s33/5.pgm",
                    "BDD/s34/1.pgm", "BDD/s34/2.pgm", "BDD/s34/3.pgm",  "BDD/s34/4.pgm", "BDD/s34/5.pgm",
                    "BDD/s35/1.pgm", "BDD/s35/2.pgm", "BDD/s35/3.pgm",  "BDD/s35/4.pgm", "BDD/s35/5.pgm",
                    "BDD/s36/1.pgm", "BDD/s36/2.pgm", "BDD/s36/3.pgm",  "BDD/s36/4.pgm", "BDD/s36/5.pgm",
                    "BDD/s37/1.pgm", "BDD/s37/2.pgm", "BDD/s37/3.pgm",  "BDD/s37/4.pgm", "BDD/s37/5.pgm",
                    "BDD/s38/1.pgm", "BDD/s38/2.pgm", "BDD/s38/3.pgm",  "BDD/s38/4.pgm", "BDD/s38/5.pgm",
                    "BDD/s39/1.pgm", "BDD/s39/2.pgm", "BDD/s39/3.pgm",  "BDD/s39/4.pgm", "BDD/s39/5.pgm",
                    "BDD/s40/1.pgm", "BDD/s40/2.pgm", "BDD/s40/3.pgm",  "BDD/s40/4.pgm", "BDD/s40/5.pgm"));

    public static ArrayList<String> bdCopie = new ArrayList<String>(
            Arrays.asList("BDD/s1/1.pgm", "BDD/s1/2.pgm", "BDD/s1/3.pgm",  "BDD/s1/4.pgm", "BDD/s1/5.pgm",
                    "BDD/s2/1.pgm", "BDD/s2/2.pgm", "BDD/s2/3.pgm",  "BDD/s2/4.pgm", "BDD/s2/5.pgm",
                    "BDD/s3/1.pgm", "BDD/s3/2.pgm", "BDD/s3/3.pgm",  "BDD/s3/4.pgm", "BDD/s3/5.pgm",
                    "BDD/s4/1.pgm", "BDD/s4/2.pgm", "BDD/s4/3.pgm",  "BDD/s4/4.pgm", "BDD/s4/5.pgm",
                    "BDD/s5/1.pgm", "BDD/s5/2.pgm", "BDD/s5/3.pgm",  "BDD/s5/4.pgm", "BDD/s5/5.pgm",
                    "BDD/s6/1.pgm", "BDD/s6/2.pgm", "BDD/s6/3.pgm",  "BDD/s6/4.pgm", "BDD/s6/5.pgm",
                    "BDD/s7/1.pgm", "BDD/s7/2.pgm", "BDD/s7/3.pgm",  "BDD/s7/4.pgm", "BDD/s7/5.pgm",
                    "BDD/s8/1.pgm", "BDD/s8/2.pgm", "BDD/s8/3.pgm",  "BDD/s8/4.pgm", "BDD/s8/5.pgm",
                    "BDD/s9/1.pgm", "BDD/s9/2.pgm", "BDD/s9/3.pgm",  "BDD/s9/4.pgm", "BDD/s9/5.pgm",
                    "BDD/s10/1.pgm", "BDD/s10/2.pgm", "BDD/s10/3.pgm",  "BDD/s10/4.pgm", "BDD/s10/5.pgm",
                    "BDD/s11/1.pgm", "BDD/s11/2.pgm", "BDD/s11/3.pgm",  "BDD/s11/4.pgm", "BDD/s11/5.pgm",
                    "BDD/s12/1.pgm", "BDD/s12/2.pgm", "BDD/s12/3.pgm",  "BDD/s12/4.pgm", "BDD/s12/5.pgm",
                    "BDD/s13/1.pgm", "BDD/s13/2.pgm", "BDD/s13/3.pgm",  "BDD/s13/4.pgm", "BDD/s13/5.pgm",
                    "BDD/s14/1.pgm", "BDD/s14/2.pgm", "BDD/s14/3.pgm",  "BDD/s14/4.pgm", "BDD/s14/5.pgm",
                    "BDD/s15/1.pgm", "BDD/s15/2.pgm", "BDD/s15/3.pgm",  "BDD/s15/4.pgm", "BDD/s15/5.pgm",
                    "BDD/s16/1.pgm", "BDD/s16/2.pgm", "BDD/s16/3.pgm",  "BDD/s16/4.pgm", "BDD/s16/5.pgm",
                    "BDD/s17/1.pgm", "BDD/s17/2.pgm", "BDD/s17/3.pgm",  "BDD/s17/4.pgm", "BDD/s17/5.pgm",
                    "BDD/s18/1.pgm", "BDD/s18/2.pgm", "BDD/s18/3.pgm",  "BDD/s18/4.pgm", "BDD/s18/5.pgm",
                    "BDD/s19/1.pgm", "BDD/s19/2.pgm", "BDD/s19/3.pgm",  "BDD/s19/4.pgm", "BDD/s19/5.pgm",
                    "BDD/s20/1.pgm", "BDD/s20/2.pgm", "BDD/s20/3.pgm",  "BDD/s20/4.pgm", "BDD/s20/5.pgm",
                    "BDD/s21/1.pgm", "BDD/s21/2.pgm", "BDD/s21/3.pgm",  "BDD/s21/4.pgm", "BDD/s21/5.pgm",
                    "BDD/s22/1.pgm", "BDD/s22/2.pgm", "BDD/s22/3.pgm",  "BDD/s22/4.pgm", "BDD/s22/5.pgm",
                    "BDD/s23/1.pgm", "BDD/s23/2.pgm", "BDD/s23/3.pgm",  "BDD/s23/4.pgm", "BDD/s23/5.pgm",
                    "BDD/s24/1.pgm", "BDD/s24/2.pgm", "BDD/s24/3.pgm",  "BDD/s24/4.pgm", "BDD/s24/5.pgm",
                    "BDD/s25/1.pgm", "BDD/s25/2.pgm", "BDD/s25/3.pgm",  "BDD/s25/4.pgm", "BDD/s25/5.pgm",
                    "BDD/s26/1.pgm", "BDD/s26/2.pgm", "BDD/s26/3.pgm",  "BDD/s26/4.pgm", "BDD/s26/5.pgm",
                    "BDD/s27/1.pgm", "BDD/s27/2.pgm", "BDD/s27/3.pgm",  "BDD/s27/4.pgm", "BDD/s27/5.pgm",
                    "BDD/s28/1.pgm", "BDD/s28/2.pgm", "BDD/s28/3.pgm",  "BDD/s28/4.pgm", "BDD/s28/5.pgm",
                    "BDD/s29/1.pgm", "BDD/s29/2.pgm", "BDD/s29/3.pgm",  "BDD/s29/4.pgm", "BDD/s29/5.pgm",
                    "BDD/s30/1.pgm", "BDD/s30/2.pgm", "BDD/s30/3.pgm",  "BDD/s30/4.pgm", "BDD/s30/5.pgm",
                    "BDD/s31/1.pgm", "BDD/s31/2.pgm", "BDD/s31/3.pgm",  "BDD/s31/4.pgm", "BDD/s31/5.pgm",
                    "BDD/s32/1.pgm", "BDD/s32/2.pgm", "BDD/s32/3.pgm",  "BDD/s32/4.pgm", "BDD/s32/5.pgm",
                    "BDD/s33/1.pgm", "BDD/s33/2.pgm", "BDD/s33/3.pgm",  "BDD/s33/4.pgm", "BDD/s33/5.pgm",
                    "BDD/s34/1.pgm", "BDD/s34/2.pgm", "BDD/s34/3.pgm",  "BDD/s34/4.pgm", "BDD/s34/5.pgm",
                    "BDD/s35/1.pgm", "BDD/s35/2.pgm", "BDD/s35/3.pgm",  "BDD/s35/4.pgm", "BDD/s35/5.pgm",
                    "BDD/s36/1.pgm", "BDD/s36/2.pgm", "BDD/s36/3.pgm",  "BDD/s36/4.pgm", "BDD/s36/5.pgm",
                    "BDD/s37/1.pgm", "BDD/s37/2.pgm", "BDD/s37/3.pgm",  "BDD/s37/4.pgm", "BDD/s37/5.pgm",
                    "BDD/s38/1.pgm", "BDD/s38/2.pgm", "BDD/s38/3.pgm",  "BDD/s38/4.pgm", "BDD/s38/5.pgm",
                    "BDD/s39/1.pgm", "BDD/s39/2.pgm", "BDD/s39/3.pgm",  "BDD/s39/4.pgm", "BDD/s39/5.pgm",
                    "BDD/s40/1.pgm", "BDD/s40/2.pgm", "BDD/s40/3.pgm",  "BDD/s40/4.pgm", "BDD/s40/5.pgm"));



    public static ArrayList<String> labels = new ArrayList<String>(
            Arrays.asList("Paul", "Paul","Paul","Paul","Paul",
                                "John", "John","John","John","John",
                                "Richard", "Richard","Richard","Richard","Richard",
                                "Jean-Michel","Jean-Michel","Jean-Michel","Jean-Michel","Jean-Michel",
                                "Max", "Max","Max","Max","Max",
                                "Lionel","Lionel","Lionel","Lionel","Lionel",
                                "Daniel","Daniel","Daniel","Daniel","Daniel",
                                "Lisa","Lisa","Lisa","Lisa","Lisa",
                                "Lucas ","Lucas ","Lucas ","Lucas ","Lucas ",
                                "Olivia","Olivia","Olivia","Olivia","Olivia",
                                "Alexander","Alexander","Alexander","Alexander","Alexander",
                                "Alex","Alex","Alex","Alex","Alex",
                                "Jacob ","Jacob ","Jacob ","Jacob ","Jacob ",
                                "Daniel","Daniel","Daniel","Daniel","Daniel",
                                "Matthew","Matthew","Matthew","Matthew","Matthew",
                                "David","David","David","David","David",
                                "Luke","Luke","Luke","Luke","Luke",
                                "Dylan","Dylan ","Dylan ","Dylan ","Dylan ",
                                "Gabriel","Gabriel","Gabriel","Gabriel","Gabriel",
                                "Andrew","Andrew","Andrew","Andrew","Andrew",
                                "Ryan","Ryan","Ryan","Ryan","Ryan",
                                "Christopher","Christopher","Christopher","Christopher","Christopher",
                                "Mateo","Mateo","Mateo","Mateo","Mateo",
                                "Thomas","Thomas","Thomas","Thomas","Thomas",
                                "Robert","Robert","Robert","Robert","Robert",
                                "Henry","Henry","Henry","Henry","Henry",
                                "Luca","Luca","Luca","Luca","Luca",
                                "Vincent","Vincent","Vincent","Vincent","Vincent",
                                "Kevin ","Kevin ","Kevin ","Kevin ","Kevin ",
                                "Ivan","Ivan","Ivan","Ivan","Ivan",
                                "Juan","Juan","Juan","Juan","Juan",
                                "Sophia","Sophia","Sophia","Sophia","Sophia",
                                "George","George","George","George","George",
                                "Abraham","Abraham","Abraham","Abraham","Abraham",
                                "Emma","Emma","Emma","Emma","Emma",
                                "Elliott","Elliott","Elliott","Elliott","Elliott",
                                "Alan","Alan","Alan","Alan","Alan",
                                "Victor","Victor","Victor","Victor","Victor",
                                "Omar","Omar","Omar","Omar","Omar",
                                "Dakota","Dakota","Dakota","Dakota","Dakota"));


    public static ArrayList<String> labelsCopie = new ArrayList<String>(
            Arrays.asList("Paul", "Paul","Paul","Paul","Paul",
                    "John", "John","John","John","John",
                    "Richard", "Richard","Richard","Richard","Richard",
                    "Jean-Michel","Jean-Michel","Jean-Michel","Jean-Michel","Jean-Michel",
                    "Max", "Max","Max","Max","Max",
                    "Lionel","Lionel","Lionel","Lionel","Lionel",
                    "Daniel","Daniel","Daniel","Daniel","Daniel",
                    "Lisa","Lisa","Lisa","Lisa","Lisa",
                    "Lucas ","Lucas ","Lucas ","Lucas ","Lucas ",
                    "Olivia","Olivia","Olivia","Olivia","Olivia",
                    "Alexander","Alexander","Alexander","Alexander","Alexander",
                    "Alex","Alex","Alex","Alex","Alex",
                    "Jacob ","Jacob ","Jacob ","Jacob ","Jacob ",
                    "Daniel","Daniel","Daniel","Daniel","Daniel",
                    "Matthew","Matthew","Matthew","Matthew","Matthew",
                    "David","David","David","David","David",
                    "Luke","Luke","Luke","Luke","Luke",
                    "Dylan","Dylan ","Dylan ","Dylan ","Dylan ",
                    "Gabriel","Gabriel","Gabriel","Gabriel","Gabriel",
                    "Andrew","Andrew","Andrew","Andrew","Andrew",
                    "Ryan","Ryan","Ryan","Ryan","Ryan",
                    "Christopher","Christopher","Christopher","Christopher","Christopher",
                    "Mateo","Mateo","Mateo","Mateo","Mateo",
                    "Thomas","Thomas","Thomas","Thomas","Thomas",
                    "Robert","Robert","Robert","Robert","Robert",
                    "Henry","Henry","Henry","Henry","Henry",
                    "Luca","Luca","Luca","Luca","Luca",
                    "Vincent","Vincent","Vincent","Vincent","Vincent",
                    "Kevin ","Kevin ","Kevin ","Kevin ","Kevin ",
                    "Ivan","Ivan","Ivan","Ivan","Ivan",
                    "Juan","Juan","Juan","Juan","Juan",
                    "Sophia","Sophia","Sophia","Sophia","Sophia",
                    "George","George","George","George","George",
                    "Abraham","Abraham","Abraham","Abraham","Abraham",
                    "Emma","Emma","Emma","Emma","Emma",
                    "Elliott","Elliott","Elliott","Elliott","Elliott",
                    "Alan","Alan","Alan","Alan","Alan",
                    "Victor","Victor","Victor","Victor","Victor",
                    "Omar","Omar","Omar","Omar","Omar",
                    "Dakota","Dakota","Dakota","Dakota","Dakota"));
}
